Unit test refactoring
Informasjonsforvaltning/a-backend-service pull request #37
Opened 2019-10-21 12:21 UTC by rannveigskjerve

2019-10-22 11:38 UTC, NilsOveTen commented on src/main/kotlin/no/brreg/informasjonsforvaltning/abackendservice/adapter/VersionAdapter.kt
> +                                  .inputStream
indent

2019-10-22 11:38 UTC, NilsOveTen commented on src/main/kotlin/no/brreg/informasjonsforvaltning/abackendservice/adapter/VersionAdapter.kt
> +                                  .inputStream
Og legg hvert funksjonskall på ny linje

2019-10-22 11:38 UTC, NilsOveTen commented on src/test/kotlin/no/brreg/informasjonsforvaltning/abackendservice/adapter/VersionAdapterGatewayTest.kt
> +     private val versionAdapter = VersionAdapter()
indent

2019-10-22 11:38 UTC, NilsOveTen commented on src/test/kotlin/no/brreg/informasjonsforvaltning/abackendservice/adapter/VersionAdapterGatewayTest.kt
> +        mockServer.stubFor(get(urlEqualTo("/version"))
strukturer dette bedre

2019-10-28 09:16 UTC, stigbd requested changes
Det ser ut til at det er implementert slik at serviceEndpoint.url må inkludere /version. Opprinnelig var det tenkt at url kun var til serviceEndpoint, og at a-backend-service sjølv legger til /version i kallet gjennom adapter. Inga stor sak. Men greit om vi endrer  før vi produskjonssetter.

2019-10-28 09:28 UTC, NilsOveTen commented
> Det ser ut til at det er implementert slik at serviceEndpoint.url må inkludere /version. Opprinnelig var det tenkt at url kun var til serviceEndpoint, og at a-backend-service sjølv legger til /version i kallet gjennom adapter. Inga stor sak. Men greit om vi endrer før vi produskjonssetter.

Null problem det, men kanskje utenfor scope for denne pr'en? Jeg kan heller fikse en annen pr med den endringen.

Originalt tenkt? Vi er ikke tankelesere ;)

2019-10-28 09:36 UTC, stigbd commented
Enig. Men eg forsøkte å antyde det i kommentaren i spesifikasjonen. Det kunne heilt klart våre meir tydeleg:
> Returns a list of endpoints (server urls)
Men det kan godt få plass i ein dedikert PR.

2019-10-28 09:40 UTC, merged